### ISSUE TITLE
Use fs Promises API

### ISSUE THREAD

**Issue by charlyx** [charlyx/pair-roulette#19]
Replace usage of [util.promisify](https://nodejs.org/api/util.html#util_util_promisify_original) with [fs.promises](https://nodejs.org/api/fs.html#fs_fs_promises_api) in [firestore.rules.spec.js](https://github.com/charlyx/pair-roulette/blob/ec5bc37700f92e7fd6ff793f56af2070afc51ac3/packages/app/src/firestore.rules.spec.js)

**Comment by SirKitboard** [comment]
Hey!
I can take this one if its available

**Comment by charlyx** [comment]
Hi @SirKitboard 👋 

Sure, go ahead!

**Comment by SirKitboard** [comment]
Hey there
So the change was pretty simple and I think i'm done, but i noticed there's not testing scripts in the package.json
What would you like me to use to test to make sure my script is working?
Also I noticed therere's no package-lock.json, would you like me to commit mine or add it to the gitignore?

**Comment by frinyvonnick** [comment]
Hi @SirKitboard, there is a [yarn.lock](https://github.com/charlyx/pair-roulette/blob/master/yarn.lock) at the root 😄 

There is a test script [here](https://github.com/charlyx/pair-roulette/blob/master/packages/app/package.json#L24) you can run to verify your change 👍 

Thank you for your contribution !

**Comment by SirKitboard** [comment]
Ah okay, thanks!
I havent used yarn before so I missed it, my bad :)

**Comment by charlyx** [comment]
You'll also need [Firebase Emulators](https://firebase.google.com/docs/rules/emulator-setup) in order to test it.
Running Cloud Firestore emulator is enough: `firebase serve --only firestore`
Then you can run `yarn test --watch` in the right directory 😄 

If `App` fails, it's OK, do not worry about it.

**Comment by charlyx** [comment]
fixed by #22
