### ISSUE TITLE
Mettre l'option pour systématiquement demander de choisir un compte à l'authentification

### ISSUE THREAD

**Issue by frinyvonnick** [charlyx/pair-roulette#6]
Lorsque je me déconnecte et me reconnecter firebase ne me demande quel compte je veux utiliser

**Comment by patou** [comment]
There is no option to do this on github : 
https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/

It's just for Google Apps : https://firebase.google.com/docs/reference/js/firebase.auth.GoogleAuthProvider.html#setcustomparameters

**Comment by frinyvonnick** [comment]
Merci @patou pour le travail de recherche 👍 

C'est dommage @charlyx les personnes qui ont plusieurs comptes GitHub par exemple perso et pro seront pénalisés. Solution de contournement ouvrir l'application en navigation privé 😢
